### ISSUE TITLE
Since Pimcore 3.1.0

### ISSUE THREAD

**Issue by ametad** [pimcore-extensions/search-php#3]
Since the update to Pimcore 3.1.0 I get an error trying to get ./sitemap.xml

Error:
Fatal error: Class 'Website_Controller_Action' not found in /var/www/ubpweb-pimcore/plugins/SearchPhp/controllers/FrontendController.php on line 4

I am looking into this... but I am fairly new to Zend and Pimcore. Hopefully somebody else can see the problem here! 

Much appreciated!
Great plugin btw!

**Comment by Hagith** [comment]
I'm did not checked 3.1 version yet, but it looks that backward compatibility related to namespaces is removed now. We should migrate all classes to use namepsaces.

**Comment by ametad** [comment]
That would be the best idea :+1:
